work_dir: ./work_dir/anubis/agcn_bone
model_saved_name: ./runs/anubis_agcn_bone

# feeder 
feeder: feeders.feeder_anubis.Feeder
train_feeder_args:
  data_path: dataset/trn_data_all_action_front.npy
  label_path: dataset/trn_label_all_action_front.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  random_rot: False
  window_size: -1
  normalization: False
  bone: True  
  vel: False

test_feeder_args:
  data_path: dataset/val_data_all_action_back.npy
  label_path: dataset/val_label_all_action_back.pkl
  debug: False
  bone: True  
  vel: False

# model 
model: model.agcn.Model
model_args:
  num_class: 102  
  num_point: 32  
  num_person: 2
  graph: graph.anubis.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.05
step: [30]
num_worker: 0
# training
device: [0]  
batch_size: 40
test_batch_size: 40
num_epoch: 50
nesterov: True