# command line: e:/skletonbasedactionrecognition/code/Anubis-benchmark/DeGCN/main.py

base_lr: 0.05
batch_size: 1
config: config/anubis/anubis.yaml
cosine_epoch: 0
device:
- 0
eval_interval: 5
feeder: feeders.feeder_anubis.Feeder
half: true
ignore_weights: []
log_interval: 100
model: model.degcn.Model
model_args:
  eta: 4
  graph: graph.anubis.Graph
  graph_args:
    labeling_mode: spatial
  k: 8
  num_class: 102
  num_person: 2
  num_point: 32
  num_stream: 2
model_saved_name: ''
nesterov: true
num_epoch: 50
num_worker: 0
optimizer: SGD
phase: train
print_log: true
save_epoch: 0
save_interval: 1
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 30
test_batch_size: 1
test_feeder_args:
  bone: true
  data_path: E:/skletonbasedactionrecognition/dataset/anubis/val_data_all_action_back.npy
  debug: false
  label_path: E:/skletonbasedactionrecognition/dataset/anubis/val_label_all_action_back.pkl
  p_interval:
  - 0.95
  split: test
  use_mmap: true
  vel: true
  window_size: -1
train_feeder_args:
  bone: true
  data_path: E:/skletonbasedactionrecognition/dataset/anubis/trn_data_all_action_front.npy
  debug: false
  label_path: E:/skletonbasedactionrecognition/dataset/anubis/trn_label_all_action_front.pkl
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: true
  split: train
  use_mmap: true
  vel: true
  window_size: -1
warm_up_epoch: 5
weight_decay: 0.0004
weights: null
work_dir: ./work_dir/anubis-ctrgcn_joint
