# command line: e:/skletonbasedactionrecognition/code/Anubis-benchmark/main-block.py

alpha: false
base_lr: 0.05
batch_size: 1
config: config/blockgcn/anubis.yaml
device:
- 0
ema: false
eval_interval: 5
feeder: feeders.feeder_anubis_blockgcn.Feeder
ignore_weights: []
joint_label: []
lambda_1: 0.0001
lambda_2: 0.1
log_interval: 100
lr_decay_rate: 0.1
model: model.blockgcn.BlockGCN.Model
model_args:
  graph: graph.anubis.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 102
  num_person: 2
  num_point: 32
model_saved_name: ''
momentum: 0.9
nesterov: true
num_epoch: 50
num_worker: 0
optimizer: SGD
phase: train
print_log: true
save_epoch: 10
save_interval: 1
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 30
test_batch_size: 1
test_feeder_args:
  bone: true
  data_path: E:/skletonbasedactionrecognition/dataset/anubis/val_data_all_action_back.npy
  debug: false
  label_path: E:/skletonbasedactionrecognition/dataset/anubis/val_label_all_action_back.pkl
  p_interval:
  - 0.95
  split: test
  use_mmap: true
  vel: true
  window_size: -1
train_feeder_args:
  bone: true
  data_path: E:/skletonbasedactionrecognition/dataset/anubis/trn_data_all_action_front.npy
  debug: false
  label_path: E:/skletonbasedactionrecognition/dataset/anubis/trn_label_all_action_front.pkl
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  use_mmap: true
  vel: true
  window_size: -1
warm_up_epoch: 5
weight_decay: 0.0004
weights: null
work_dir: ./work_dir/anubis/xset/ctrgcn_joint
